# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjtCvwR3O_YzmpNj2gGydj3zIT8R2ro8
"""

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

results = model.train(
    data="/kaggle/working/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    seed=42,
    workers=2,
    name="Pest-disease",
    project="/kaggle/working/experiments",
    device=0,
    save=True,
    plots=True,
)